version: "3"

services:
  api:
    container_name: vank-rest-api
    restart: always
    build: .
    command: npm run dev
    ports:
      - "1337:1337"
    volumes:
      - ./:/usr/src/app
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none

  redis:
    container_name: redis-db
    image: redis
    ports:
      - "6379:6379"
    logging:
      driver: none
